# CAELESTIA_SHELL_AW_MANAGED=io.github.conlongnhong.caelestia-shell-aw
# Autostart Caelestia Shell AW.
exec-once = caelestia shell -d

# Keep this order: a window must float before it can be centered.
# Wayland AppId: io.github.conlongnhong.caelestia-shell-aw
windowrule = float true, match:class ^io\.github\.conlongnhong\.caelestia-shell-aw$
windowrule = center true, match:class ^io\.github\.conlongnhong\.caelestia-shell-aw$
